services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: casaradm
      POSTGRES_PASSWORD: '69t;8:&s<Lp3'
      POSTGRES_DB: thoughts
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: casar-thoughts-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://casaradm:69t;8:&s<Lp3@postgres:5432/thoughts'
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: casaradm
      DB_PASSWORD: '69t;8:&s<Lp3'
      DB_NAME: thoughts
      NODE_ENV: production
      TEXT_PROCESSING_API_URL: 'http://text-processing.com/api/sentiment'
      ALLOW_TEXT_PROCESSING: true
    ports:
      - '3000:3000'
    command: >
      sh -c "
      yarn migration:run &&
      yarn migration:seed &&
      node /app/dist/main"
    volumes:
      - /app/node_modules

volumes:
  postgres_data:
