version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://user:password@postgres:5432/mydatabase'
    ports:
      - '3000:3000'
    command: ['sh', '-c', 'npm run start:prod']
    volumes:
      - .:/app
      - /app/node_modules

  migrations:
    build: .
    container_name: nestjs_migrations
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://user:password@postgres:5432/mydatabase'
    command: ['sh', '-c', 'npx prisma migrate deploy && npm run seed']
    restart: on-failure

volumes:
  postgres_data:
